# resolve-type-names: false

class ::Book < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Book, ::Book::ActiveRecord_Relation, ::Integer]

  module ::Book::GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::Integer

    def id_for_database: () -> ::Integer

    def order_id: () -> ::Integer?

    def order_id=: (::Integer?) -> ::Integer?

    def order_id?: () -> bool

    def order_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def order_id_change: () -> [ ::Integer?, ::Integer? ]

    def order_id_will_change!: () -> void

    def order_id_was: () -> ::Integer?

    def order_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def order_id_previous_change: () -> ::Array[::Integer?]?

    def order_id_previously_was: () -> ::Integer?

    def order_id_before_last_save: () -> ::Integer?

    def order_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def order_id_in_database: () -> ::Integer?

    def saved_change_to_order_id: () -> ::Array[::Integer?]?

    def saved_change_to_order_id?: () -> bool

    def will_save_change_to_order_id?: () -> bool

    def restore_order_id!: () -> void

    def clear_order_id_change: () -> void

    def order_id_before_type_cast: () -> ::Integer?

    def order_id_for_database: () -> ::Integer?

    def price: () -> ::Integer?

    def price=: (::Integer?) -> ::Integer?

    def price?: () -> bool

    def price_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def price_change: () -> [ ::Integer?, ::Integer? ]

    def price_will_change!: () -> void

    def price_was: () -> ::Integer?

    def price_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def price_previous_change: () -> ::Array[::Integer?]?

    def price_previously_was: () -> ::Integer?

    def price_before_last_save: () -> ::Integer?

    def price_change_to_be_saved: () -> ::Array[::Integer?]?

    def price_in_database: () -> ::Integer?

    def saved_change_to_price: () -> ::Array[::Integer?]?

    def saved_change_to_price?: () -> bool

    def will_save_change_to_price?: () -> bool

    def restore_price!: () -> void

    def clear_price_change: () -> void

    def price_before_type_cast: () -> ::Integer?

    def price_for_database: () -> ::Integer?

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time

    def currency_code: () -> ::String

    def currency_code=: (::String) -> ::String

    def currency_code?: () -> bool

    def currency_code_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def currency_code_change: () -> [ ::String?, ::String? ]

    def currency_code_will_change!: () -> void

    def currency_code_was: () -> ::String?

    def currency_code_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def currency_code_previous_change: () -> ::Array[::String?]?

    def currency_code_previously_was: () -> ::String?

    def currency_code_before_last_save: () -> ::String?

    def currency_code_change_to_be_saved: () -> ::Array[::String?]?

    def currency_code_in_database: () -> ::String?

    def saved_change_to_currency_code: () -> ::Array[::String?]?

    def saved_change_to_currency_code?: () -> bool

    def will_save_change_to_currency_code?: () -> bool

    def restore_currency_code!: () -> void

    def clear_currency_code_change: () -> void

    def currency_code_before_type_cast: () -> ::String

    def currency_code_for_database: () -> ::String
  end
  include ::Book::GeneratedAttributeMethods
  module ::Book::GeneratedAliasAttributeMethods
    include ::Book::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Book::GeneratedAliasAttributeMethods

  def order: () -> ::Order
  def order=: (::Order?) -> ::Order?
  def reload_order: () -> ::Order?
  def build_order: (untyped) -> ::Order
  def create_order: (untyped) -> ::Order
  def create_order!: (untyped) -> ::Order
  def money: () -> ::Book::Money
  def money=: (::Book::Money) -> ::Book::Money
  module ::Book::GeneratedAssociationMethods
  end
  include ::Book::GeneratedAssociationMethods

  def jpy!: () -> bool
  def jpy?: () -> bool
  def usd!: () -> bool
  def usd?: () -> bool
  def eur!: () -> bool
  def eur?: () -> bool
  def self.currency_codes: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]
  def self.jpy: () -> ::Book::ActiveRecord_Relation
  def self.not_jpy: () -> ::Book::ActiveRecord_Relation
  def self.usd: () -> ::Book::ActiveRecord_Relation
  def self.not_usd: () -> ::Book::ActiveRecord_Relation
  def self.eur: () -> ::Book::ActiveRecord_Relation
  def self.not_eur: () -> ::Book::ActiveRecord_Relation

  module ::Book::GeneratedRelationMethods
    def currency_codes: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]

    def jpy: () -> ::Book::ActiveRecord_Relation

    def not_jpy: () -> ::Book::ActiveRecord_Relation

    def usd: () -> ::Book::ActiveRecord_Relation

    def not_usd: () -> ::Book::ActiveRecord_Relation

    def eur: () -> ::Book::ActiveRecord_Relation

    def not_eur: () -> ::Book::ActiveRecord_Relation
  end

  class ::Book::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Book]
    include ::Book::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Book, ::Integer]
  end

  class ::Book::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Book]
    include ::Book::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Book, ::Integer]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Book
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Book]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Book
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Book]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Book
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Book]
    def reload: () -> ::Array[::Book]

    def replace: (::Array[::Book]) -> void
    def delete: (*::Book | ::Integer) -> ::Array[::Book]
    def destroy: (*::Book | ::Integer) -> ::Array[::Book]
    def <<: (*::Book | ::Array[::Book]) -> self
    def prepend: (*::Book | ::Array[::Book]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Order < ::ApplicationRecord
end
class ::Book::Money < ::Object
end
class ::Book < ::ApplicationRecord
end
