# resolve-type-names: false

interface ::_RbsRailsPathHelpers
  def rails_info_properties_path: (*untyped) -> ::String
  def rails_info_routes_path: (*untyped) -> ::String
  def rails_info_path: (*untyped) -> ::String
  def users_path: (*untyped) -> ::String
  def new_user_path: (*untyped) -> ::String
  def edit_user_path: (*untyped) -> ::String
  def user_path: (*untyped) -> ::String
  def rails_service_blob_path: (*untyped) -> ::String
  def rails_service_blob_proxy_path: (*untyped) -> ::String
  def rails_blob_representation_path: (*untyped) -> ::String
  def rails_blob_representation_proxy_path: (*untyped) -> ::String
  def rails_disk_service_path: (*untyped) -> ::String
  def update_rails_disk_service_path: (*untyped) -> ::String
  def rails_direct_uploads_path: (*untyped) -> ::String
  def rails_representation_path: (*untyped) -> ::String
  def rails_blob_path: (*untyped) -> ::String
  def rails_storage_proxy_path: (*untyped) -> ::String
  def rails_storage_redirect_path: (*untyped) -> ::String
  def rails_info_properties_url: (*untyped) -> ::String
  def rails_info_routes_url: (*untyped) -> ::String
  def rails_info_url: (*untyped) -> ::String
  def users_url: (*untyped) -> ::String
  def new_user_url: (*untyped) -> ::String
  def edit_user_url: (*untyped) -> ::String
  def user_url: (*untyped) -> ::String
  def rails_service_blob_url: (*untyped) -> ::String
  def rails_service_blob_proxy_url: (*untyped) -> ::String
  def rails_blob_representation_url: (*untyped) -> ::String
  def rails_blob_representation_proxy_url: (*untyped) -> ::String
  def rails_disk_service_url: (*untyped) -> ::String
  def update_rails_disk_service_url: (*untyped) -> ::String
  def rails_direct_uploads_url: (*untyped) -> ::String
  def rails_representation_url: (*untyped) -> ::String
  def rails_blob_url: (*untyped) -> ::String
  def rails_storage_proxy_url: (*untyped) -> ::String
  def rails_storage_redirect_url: (*untyped) -> ::String
end

module ::ActionController
  class ::ActionController::Base
    include ::_RbsRailsPathHelpers
  end
end
