source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 7.2.0'
gem 'sqlite3', '~> 1.4'
gem 'puma'
gem 'bootsnap', require: false
gem 'bcrypt'

# https://bugs.ruby-lang.org/issues/20859
gem 'base64'

gem 'packs-rails'

# Gem that creates external library models for testing
gem 'audited'

gem 'rbs_rails', path: '../../'
