source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 7.0.0'
gem 'sqlite3', '~> 1.4'
gem 'puma'
gem 'bootsnap', require: false
gem 'bcrypt'

# https://github.com/ruby-concurrency/concurrent-ruby/pull/1062
gem 'concurrent-ruby', '1.3.4'

# https://bugs.ruby-lang.org/issues/20859
gem 'base64'

# They are bundled gems since Ruby 3.4
gem 'bigdecimal'
gem 'mutex_m'

# They are bundled gems since Ruby 3.5
gem 'benchmark'

gem 'packs-rails'

# Gem that creates external library models for testing
gem 'audited'

gem 'rbs_rails', path: '../../'
