target :app do
  signature 'sig'
  check "app/models"

  repo_path ENV['RBS_REPO_DIR'] if ENV['RBS_REPO_DIR']

  # rbs collection
  # TODO: Move the implementation to Steep
  lock = RBS::Collection::Config.lockfile_of(Pathname('../../rbs_collection.yaml'))
  repo_path lock.repo_path

  lock.gems.each do |gem|
    library "#{gem['name']}:#{gem['version']}"
  end
end
