interface _ActionController_API_and_Base
  def request: () -> untyped
  def params: () -> untyped
  def session: () -> untyped
  def cookies: () -> untyped
  def flash: () -> untyped
  def render: (*untyped) -> void
  def redirect_to: (*untyped) -> void
end

interface _ActionController_API_and_Base_singletion
  # hooks
  def before_action: (*untyped) -> void
  def around_action: (*untyped) -> void
  def after_action: (*untyped) -> void
  def skip_before_action: (*untyped) -> void
  def skip_around_action: (*untyped) -> void
  def skip_after_action: (*untyped) -> void
  def prepend_before_action: (*untyped) -> void
  def prepend_around_action: (*untyped) -> void
  def prepend_after_action: (*untyped) -> void
  def append_before_action: (*untyped) -> void
  def append_around_action: (*untyped) -> void
  def append_after_action: (*untyped) -> void

  def rescue_from: (*Class, ?with: Symbol | Proc) { (Exception) -> void } -> void
end

class AbstractController::Base
end

class ActionController::Metal < AbstractController::Base
end

class ActionController::Base < ActionController::Metal
  include _ActionController_API_and_Base
  extend _ActionController_API_and_Base_singletion
  extend ActionView::Layouts::ClassMethods
end

class ActionController::API < ActionController::Metal
  include _ActionController_API_and_Base
  extend _ActionController_API_and_Base_singletion
end
