extension Object (ActiveSupport)
  def blank?: () -> bool
  def present?: () -> bool
  def presence: () -> self
end

extension String (ActiveSupport)
  def indent: (Integer, ?String?, bool) -> String
  def indent!: (Integer, ?String?, bool) -> String
  def underscore: () -> String
end

extension Integer (ActiveSupport)
  def days: () -> untyped
  def day: () -> untyped
  def year: () -> untyped
  def years: () -> untyped
  def month: () -> untyped
  def months: () -> untyped
  def week: () -> untyped
  def weeks: () -> untyped
  def minute: () -> untyped
  def minutes: () -> untyped
end

extension Time (ActiveSupport)
  def self.zone: () -> untyped
end
