module Rack
  class Server
  end

  class Response
    module Helpers
    end
  end

  class Request
    module Helpers
    end

    module Env
    end
  end

  module Session
    module Abstract
      class SessionHash
      end

      class PersistedSecure
        class SecureSessionHash
        end
      end

      class Persisted
      end
    end

    class SessionId
    end

    class Dalli
    end
  end

  module Cache
    class MetaStore
    end

    class EntityStore
    end
  end
end
