module Rails
  overload def self.env: () -> ActiveSupport::StringInquirer

  module Dom
    module Testing
      module Assertions
      end
    end
  end
end

class Rails::Application
  def routes: () -> untyped
end
