
module ActionView
  class OutputBuffer < ActiveSupport::SafeBuffer
    # alias bug: https://github.com/ruby/rbs/issues/458
    def safe_concat: (untyped value) -> untyped
  end

  class LookupContext
    class DetailsKey
      # alias bug: https://github.com/ruby/rbs/issues/458
      def equal?: (untyped other) -> bool
    end
  end

  class Resolver
    # Defined with meta-programming
    def self.caching: () -> untyped
  end
end
